#!/bin/sh
#check environment partition.
if [ ! -e /dev/mmcblk0p3 ] ; then
    /bin/mknod /dev/mmcblk0p3 b `cat /proc/devices | grep mmc | awk '{printf $1}'` 3
fi
if [ ! -e /dev/mmcblk0p2 ] ; then
    /bin/mknod /dev/mmcblk0p2 b `cat /proc/devices | grep mmc | awk '{printf $1}'` 2
fi

/etc/init.d/splashfb start
