#!/bin/sh
. /etc/rc.d/init.d/splash-utils.sh

${SPLASH} prg 50
${SPLASH} clear_log
${SPLASH} log "Starting user services..."

if [ -f /etc/init.d/drm.sh ]; then
	/etc/init.d/drm.sh
fi

if [ -f /root/rc.user ]; then
	/bin/sh /root/rc.user
fi
