#!/bin/sh

#need to create dir /mnt/Userfs/bt
mkdir -p /mnt/Userfs/bt

insmod /usr/local/lib/modules/bthid.ko
insmod /usr/local/lib/modules/btusb.ko

echo "start bsa_server_respawn_script.sh"

/etc/init.d/bsa_server_respawn_script.sh &
